import Head from "next/head";
import Home from "../components/Home";
import Footer from "../components/Footer";
import CallToAction from "../components/CallToAction";
import Header from "../components/Header";

export default function Index() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Home />
      <CallToAction />
      <Footer />
    </>
  );
}
